### ISSUE TITLE
Exemplar storage does not store samples as proposed

### ISSUE THREAD

**Issue by xingyifei2016** [scok30/MAE-CIL#4]
Hello authors,

Firstly, I really appreciate the code release for reproduction purposes. However, when executing the code, I noticed that running the given code with the mae-memories (stored in the folder mae-memory, in the form of npy files each storing 5000 samples) will yield an error, where the load function inside the rehearsal.py file will have an assertion error such that the saved npy memory size (5000) is more than the expected memory size (2000). One of the claims in the paper is that by using MAE, we can store masked versions of exemplars, yielding a potential 4x increase in stored samples (with 75% masking). In this case, 5000 samples (which is the maximum image per training class) should be stored as exemplars. However, upon close inspection of the code, I do not see how the code saves 5000 samples; in debug mode, it only saves 2000 samples instead. Also, the code does not support masking out the images before storage, which is what the paper had proposed. Thus, I am wondering how the code achieves storing the 5000 masked samples for replay. 

Most importantly, given the current code, how do I avoid the assertion error due to mae-memory having 5000 samples per npy file to reproduce the results?

Please advise. Thank you.

**Comment by xingyifei2016** [comment]
Never mind, this question was answered by the first thread. Simply put, this part of the code is not released yet.

**Comment by xingyifei2016** [comment]
Just as a follow-up, if I run this code as given (also by removing the pre-saved mae-memory folder, as including this folder gives an assertion error), the overall test accuracy on task 2 is already only around 50%, which does not match what the paper has provided. Please advise.

**Comment by scok30** [comment]
OK, we will re-check the local and uploaded versions, and we will modify them if they are different. We apologize for the inconvenience caused to you.

**Comment by xingyifei2016** [comment]
Thank you so much for your help! I finished running the script, which took 3 days and 12 hours on a 4GPU v100 machine, and achieved an overall 43% accuracy at the last task (again, this is done by removing the mae-memory folder as the current 5000-sample npy file gives an assertion error). I am also curious if you can provide details about which segment of the code is relatively slower than others, as the dytox baseline takes around 11 hours to finish as a comparison. Thank you again, and I really appreciate your answers!
